import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Forum Dicoding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} grid md:grid-cols-12 gap-2 bg-white`}>
        <div className="md:col-span-3 sticky">
          <Sidebar />
        </div>
        <div className="md:col-span-9">{children}</div>
      </body>
    </html>
  );
}
